### ISSUE TITLE
Tracking Which Users Enter and Exit Server

### ISSUE THREAD

**Issue by Hymmnos** [NeonLights10/Epsilon#12]
It would be an interesting enhancement for the bot to post in a designated channel when a user enters or exists the server. 

The MEE6 bot's Welcome plugin has this feature for reference: [Link](https://help.mee6.xyz/en/article/send-a-message-when-a-member-leaves-your-server-1kxc6h/)

**Comment by NeonLights10** [comment]
This will be implemented alongside #3
